name: Update

on:
  repository_dispatch:
    types: [update-documentation]

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Update submodule
        run: git submodule update --init --recursive --remote repositories/${{ github.event.client_payload.repo }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: Update ${{ github.event.client_payload.repo }} documentation to ${{github.event.client_payload.ref}}'
          fetch: false
          default_author: user_info
          author_name: ReVanced Bot
          author_email: contact@revanced.app
          committer_name: ReVanced Bot
          committer_email: contact@revanced.app
